### ISSUE TITLE
Setting Option to Close Command Window

### ISSUE THREAD

**Issue by AlexanderAdelAU** [tobysmith568/run-in-powershell#11]
I see no way to automatically close the terminal window once the batch file has finished.   Is this a possible?

**Comment by tobysmith568** [comment]
Hey @AlexanderAdelAU 

Sorry it's taken me well over a year to respond to you.

In the recent PR #19 I've added a setting to the options that allows for this behaviour.
I couldn't find a decent way to include the option on a _per-run_ basis - but hopefully this is something like what you were looking for?

<img width="603" alt="image" src="https://github.com/tobysmith568/run-in-powershell/assets/22356255/1104574e-d417-4b16-ab99-8989940f4f20">


I'm going to close this as resolved but please feel free to reply if there was specifically something else that you had in mind and would still be interested in.

**Comment by AlexanderAdelAU** [comment]
Thankyou
