### ISSUE TITLE
How to start Windows PowerShell x64?

### ISSUE THREAD

**Issue by SamLowryMOI** [tobysmith568/run-in-powershell#14]
It is easily possible to start Powershell 7 (x64) with the entry `C:\Program Files\PowerShell\7\pwsh.exe` under `PowerShell Core Location`.

But how do I start PowerShell (x64)? Neither the entry `C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe` nor the entry `C:\Windows\syswow64\WindowsPowerShell\v1.0\powershell.exe` are successful. The 32-bit version is always started. And there, for example, the registry looks quite different. A script that should run under Windows 64-bit cannot be tried then. Unfortunately. Because I find this extension pretty great.

Operating system: Windows 10 64-bit.

**Comment by SamLowryMOI** [comment]
I solved it. I worked in a 32-bit version of VS Code to test some things. Of course, this version only sees the content of the path `C:\Windows\syswow64\` under `C:\Windows\System32\` (`C:\Windows\syswow64\` does not exist there). Therefore, calling `powershell.exe` (or `C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe`) always runs the 32-bit version.

To still be able to run the 64-bit version, you can simply create a symbolic link somewhere, e.g. with `C:\>mklink /D WindowsPowerShell C:\Windows\System32\WindowsPowerShell\v1.0`. Then you can run the 64-bit version of Windows Powershell in a 32-bit version of VS Code by calling `C:\WindowsPowerShell\powershell.exe`.

**Comment by tobysmith568** [comment]
Hey :)

Happy to hear that you resolve this
